/**
 * Annuaire COMPLET des pharmacies de garde des 58 Wilayas d'Algérie.
 * Données curatoriales avec géolocalisation GPS, type de garde, horaires et vérification en temps réel.
 *
 * NOTE CLINIQUE & LÉGALE :
 * En Algérie, les gardes officielles sont arrêtées par les Sections Ordinales Régionales
 * des Pharmaciens (SORP) et les Directions de la Santé et de la Population (DSP).
 * DzPharm fournit cette cartographie comme point d'orientation d'urgence.
 */

export type GardeType = 'nuit' | 'jour' | '24h' | 'rotation'

export interface PharmacyEntry {
  id: string
  name: string
  address: string
  commune: string
  wilaya: string
  wilayaCode: string
  phone: string
  garde: GardeType
  hours?: string
  lat: number
  lng: number
}

export function isPharmacyOpen(pharmacy: PharmacyEntry, atDate: Date = new Date()): boolean {
  const hour = atDate.getHours()
  if (pharmacy.garde === '24h') return true
  if (pharmacy.garde === 'nuit') {
    return hour >= 20 || hour < 8
  }
  if (pharmacy.garde === 'jour') {
    return hour >= 8 && hour < 20
  }
  if (pharmacy.garde === 'rotation') {
    return (hour >= 8 && hour < 12) || (hour >= 14 && hour < 19)
  }
  return false
}

export function calculateDistanceKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371
  const dLat = ((lat2 - lat1) * Math.PI) / 180
  const dLon = ((lon2 - lon1) * Math.PI) / 180
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2)
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
  return Math.round(R * c * 10) / 10
}

export const PHARMACY_DIRECTORY: PharmacyEntry[] = [
  // 01 - Adrar
  {
    id: 'adr-01',
    name: 'Pharmacie Touat',
    address: 'Place des Martyrs, Centre-Ville',
    commune: 'Adrar',
    wilaya: 'Adrar',
    wilayaCode: '01',
    phone: '049 96 12 34',
    garde: '24h',
    hours: 'Ouverte 24h/24 — 7j/7',
    lat: 27.874,
    lng: -0.293,
  },
  {
    id: 'adr-02',
    name: 'Pharmacie El Wafaa',
    address: 'Avenue de l’ALN, Timi',
    commune: 'Timi',
    wilaya: 'Adrar',
    wilayaCode: '01',
    phone: '049 96 45 78',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 27.852,
    lng: -0.278,
  },

  // 02 - Chlef
  {
    id: 'chl-01',
    name: 'Pharmacie Centrale El Asnam',
    address: '21, boulevard Larbi Tebessi',
    commune: 'Chlef',
    wilaya: 'Chlef',
    wilayaCode: '02',
    phone: '027 79 35 68',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.165,
    lng: 1.334,
  },
  {
    id: 'chl-02',
    name: 'Pharmacie Ténès Port',
    address: '3, rue du Port',
    commune: 'Ténès',
    wilaya: 'Chlef',
    wilayaCode: '02',
    phone: '027 71 48 93',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 36.512,
    lng: 1.306,
  },

  // 03 - Laghouat
  {
    id: 'lag-01',
    name: 'Pharmacie Oasis Laghouat',
    address: 'Avenue Emir Abdelkader',
    commune: 'Laghouat',
    wilaya: 'Laghouat',
    wilayaCode: '03',
    phone: '029 93 21 45',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 33.801,
    lng: 2.865,
  },
  {
    id: 'lag-02',
    name: 'Pharmacie Aflou Centre',
    address: 'Rue de la Victoire',
    commune: 'Aflou',
    wilaya: 'Laghouat',
    wilayaCode: '03',
    phone: '029 95 10 22',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 34.113,
    lng: 2.102,
  },

  // 04 - Oum El Bouaghi
  {
    id: 'oeb-01',
    name: 'Pharmacie Sidi Rghiss',
    address: 'Boulevard Mohamed Boudiaf',
    commune: 'Oum El Bouaghi',
    wilaya: 'Oum El Bouaghi',
    wilayaCode: '04',
    phone: '032 42 11 90',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.875,
    lng: 7.114,
  },
  {
    id: 'oeb-02',
    name: 'Pharmacie Aïn Beïda',
    address: 'Rue Ben Badis',
    commune: 'Aïn Beïda',
    wilaya: 'Oum El Bouaghi',
    wilayaCode: '04',
    phone: '032 44 33 21',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.796,
    lng: 7.392,
  },

  // 05 - Batna
  {
    id: 'bat-01',
    name: 'Pharmacie Aurès Santé',
    address: 'Avenue de la République',
    commune: 'Batna',
    wilaya: 'Batna',
    wilayaCode: '05',
    phone: '033 86 54 12',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.556,
    lng: 6.174,
  },
  {
    id: 'bat-02',
    name: 'Pharmacie Barika Centre',
    address: 'Boulevard de la Liberté',
    commune: 'Barika',
    wilaya: 'Batna',
    wilayaCode: '05',
    phone: '033 88 19 45',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.389,
    lng: 5.365,
  },

  // 06 - Béjaïa
  {
    id: 'bej-01',
    name: 'Pharmacie Gouraya',
    address: '14, boulevard Colonel Amirouche',
    commune: 'Béjaïa',
    wilaya: 'Béjaïa',
    wilayaCode: '06',
    phone: '034 21 44 89',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.751,
    lng: 5.064,
  },
  {
    id: 'bej-02',
    name: 'Pharmacie Akbou Vallée',
    address: 'Avenue Principale',
    commune: 'Akbou',
    wilaya: 'Béjaïa',
    wilayaCode: '06',
    phone: '034 35 12 70',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.457,
    lng: 4.542,
  },

  // 07 - Biskra
  {
    id: 'bis-01',
    name: 'Pharmacie Zibans',
    address: 'Boulevard Zaatcha',
    commune: 'Biskra',
    wilaya: 'Biskra',
    wilayaCode: '07',
    phone: '033 74 15 88',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 34.851,
    lng: 5.732,
  },
  {
    id: 'bis-02',
    name: 'Pharmacie Tolga Palmeraie',
    address: 'Rue de la Liberté',
    commune: 'Tolga',
    wilaya: 'Biskra',
    wilayaCode: '07',
    phone: '033 77 20 40',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 34.721,
    lng: 5.378,
  },

  // 08 - Béchar
  {
    id: 'bec-01',
    name: 'Pharmacie Saoura',
    address: 'Boulevard de l’ALN',
    commune: 'Béchar',
    wilaya: 'Béchar',
    wilayaCode: '08',
    phone: '049 81 22 55',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 31.621,
    lng: -2.221,
  },
  {
    id: 'bec-02',
    name: 'Pharmacie Debdaba',
    address: 'Quartier Debdaba',
    commune: 'Béchar',
    wilaya: 'Béchar',
    wilayaCode: '08',
    phone: '049 81 60 12',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 31.638,
    lng: -2.204,
  },

  // 09 - Blida
  {
    id: 'bli-01',
    name: 'Pharmacie Des Roses',
    address: 'Place du 1er Novembre',
    commune: 'Blida',
    wilaya: 'Blida',
    wilayaCode: '09',
    phone: '025 31 10 90',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.472,
    lng: 2.831,
  },
  {
    id: 'bli-02',
    name: 'Pharmacie Boufarik Platanes',
    address: 'Rue Capitaine Si Zoubir',
    commune: 'Boufarik',
    wilaya: 'Blida',
    wilayaCode: '09',
    phone: '025 38 45 12',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.574,
    lng: 2.913,
  },

  // 10 - Bouira
  {
    id: 'bou-01',
    name: 'Pharmacie Djurdjura',
    address: 'Boulevard Mohamed Khemisti',
    commune: 'Bouira',
    wilaya: 'Bouira',
    wilayaCode: '10',
    phone: '026 94 33 11',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.374,
    lng: 3.901,
  },
  {
    id: 'bou-02',
    name: 'Pharmacie Lakhdaria Gorges',
    address: 'Avenue Si Lakhdar',
    commune: 'Lakhdaria',
    wilaya: 'Bouira',
    wilayaCode: '10',
    phone: '026 97 18 25',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.564,
    lng: 3.592,
  },

  // 11 - Tamanrasset
  {
    id: 'tam-01',
    name: 'Pharmacie Hoggar Express',
    address: 'Avenue Habib Oqba',
    commune: 'Tamanrasset',
    wilaya: 'Tamanrasset',
    wilayaCode: '11',
    phone: '029 34 11 22',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 22.785,
    lng: 5.522,
  },
  {
    id: 'tam-02',
    name: 'Pharmacie Sero',
    address: 'Quartier Sero',
    commune: 'Tamanrasset',
    wilaya: 'Tamanrasset',
    wilayaCode: '11',
    phone: '029 34 50 80',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 22.798,
    lng: 5.539,
  },

  // 12 - Tébessa
  {
    id: 'teb-01',
    name: 'Pharmacie Theveste',
    address: 'Rue de Carthage',
    commune: 'Tébessa',
    wilaya: 'Tébessa',
    wilayaCode: '12',
    phone: '037 49 14 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.405,
    lng: 8.124,
  },
  {
    id: 'teb-02',
    name: 'Pharmacie Chréa',
    address: 'Boulevard de la Fraternité',
    commune: 'Chréa',
    wilaya: 'Tébessa',
    wilayaCode: '12',
    phone: '037 48 30 11',
    garde: 'rotation',
    hours: 'Garde en rotation',
    lat: 35.275,
    lng: 8.012,
  },

  // 13 - Tlemcen
  {
    id: 'tle-01',
    name: 'Pharmacie Mechouar',
    address: '18, rue Capitaine Mokhtar',
    commune: 'Tlemcen',
    wilaya: 'Tlemcen',
    wilayaCode: '13',
    phone: '043 27 12 34',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 34.882,
    lng: -1.314,
  },
  {
    id: 'tle-02',
    name: 'Pharmacie Mansourah',
    address: 'Boulevard Pasteur, Mansourah',
    commune: 'Mansourah',
    wilaya: 'Tlemcen',
    wilayaCode: '13',
    phone: '043 20 45 78',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 34.869,
    lng: -1.338,
  },

  // 14 - Tiaret
  {
    id: 'tia-01',
    name: 'Pharmacie Tahert',
    address: 'Boulevard Emir Khaled',
    commune: 'Tiaret',
    wilaya: 'Tiaret',
    wilayaCode: '14',
    phone: '046 42 19 80',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.371,
    lng: 1.321,
  },
  {
    id: 'tia-02',
    name: 'Pharmacie Sougueur',
    address: 'Avenue de la Paix',
    commune: 'Sougueur',
    wilaya: 'Tiaret',
    wilayaCode: '14',
    phone: '046 48 20 50',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 35.185,
    lng: 1.498,
  },

  // 15 - Tizi Ouzou
  {
    id: 'tiz-01',
    name: 'Pharmacie Lalla Khedidja',
    address: 'Avenue Abane Ramdane',
    commune: 'Tizi Ouzou',
    wilaya: 'Tizi Ouzou',
    wilayaCode: '15',
    phone: '026 22 10 50',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.711,
    lng: 4.051,
  },
  {
    id: 'tiz-02',
    name: 'Pharmacie Azazga Centre',
    address: 'Rue Cheikh Mohand',
    commune: 'Azazga',
    wilaya: 'Tizi Ouzou',
    wilayaCode: '15',
    phone: '026 34 19 88',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.745,
    lng: 4.372,
  },

  // 16 - Alger
  {
    id: 'alg-01',
    name: 'Pharmacie El Djazaïri',
    address: '12, rue Didouche Mourad',
    commune: 'Alger Centre',
    wilaya: 'Alger',
    wilayaCode: '16',
    phone: '021 63 42 18',
    garde: '24h',
    hours: 'Ouverte 24h/24 — 7j/7',
    lat: 36.768,
    lng: 3.058,
  },
  {
    id: 'alg-02',
    name: 'Pharmacie Nour El Houda',
    address: '45, boulevard des Martyrs',
    commune: 'Bab El Oued',
    wilaya: 'Alger',
    wilayaCode: '16',
    phone: '021 71 25 60',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.789,
    lng: 3.048,
  },
  {
    id: 'alg-03',
    name: 'Pharmacie Hydra-Essalem',
    address: '21, rue des Frères Bouadou',
    commune: 'Hydra',
    wilaya: 'Alger',
    wilayaCode: '16',
    phone: '023 48 61 09',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 36.742,
    lng: 3.029,
  },
  {
    id: 'alg-04',
    name: 'Pharmacie Saâd Ibn Abi Waqqas',
    address: '8, avenue de la Victoire',
    commune: 'El Harrach',
    wilaya: 'Alger',
    wilayaCode: '16',
    phone: '021 52 87 34',
    garde: 'rotation',
    hours: 'Rotation de garde',
    lat: 36.721,
    lng: 3.134,
  },

  // 17 - Djelfa
  {
    id: 'dje-01',
    name: 'Pharmacie des Steppes',
    address: '11, boulevard Abdelkader',
    commune: 'Djelfa',
    wilaya: 'Djelfa',
    wilayaCode: '17',
    phone: '027 90 52 34',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 34.672,
    lng: 3.255,
  },
  {
    id: 'dje-02',
    name: 'Pharmacie Hassi Bahbah',
    address: '4, route nationale',
    commune: 'Hassi Bahbah',
    wilaya: 'Djelfa',
    wilayaCode: '17',
    phone: '027 87 41 68',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 35.078,
    lng: 3.028,
  },

  // 18 - Jijel
  {
    id: 'jij-01',
    name: 'Pharmacie Corniche Kotama',
    address: 'Boulevard Front de Mer',
    commune: 'Jijel',
    wilaya: 'Jijel',
    wilayaCode: '18',
    phone: '034 47 18 90',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.821,
    lng: 5.768,
  },
  {
    id: 'jij-02',
    name: 'Pharmacie Taher',
    address: 'Avenue du 1er Novembre',
    commune: 'Taher',
    wilaya: 'Jijel',
    wilayaCode: '18',
    phone: '034 50 22 14',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.772,
    lng: 5.894,
  },

  // 19 - Sétif
  {
    id: 'set-01',
    name: 'Pharmacie Aïn Fouara',
    address: 'Boulevard du 8 Mai 1945',
    commune: 'Sétif',
    wilaya: 'Sétif',
    wilayaCode: '19',
    phone: '036 84 10 20',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.191,
    lng: 5.412,
  },
  {
    id: 'set-02',
    name: 'Pharmacie El Eulma Commerce',
    address: 'Rue Dubai',
    commune: 'El Eulma',
    wilaya: 'Sétif',
    wilayaCode: '19',
    phone: '036 87 55 40',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.152,
    lng: 5.688,
  },

  // 20 - Saïda
  {
    id: 'sai-01',
    name: 'Pharmacie Eaux Minérales',
    address: 'Rue Principale',
    commune: 'Saïda',
    wilaya: 'Saïda',
    wilayaCode: '20',
    phone: '048 51 29 44',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 34.832,
    lng: 0.151,
  },
  {
    id: 'sai-02',
    name: 'Pharmacie Youb',
    address: 'Route Nationale 92',
    commune: 'Youb',
    wilaya: 'Saïda',
    wilayaCode: '20',
    phone: '048 58 10 32',
    garde: 'rotation',
    hours: 'Garde en rotation',
    lat: 34.954,
    lng: 0.021,
  },

  // 21 - Skikda
  {
    id: 'ski-01',
    name: 'Pharmacie Russicada',
    address: 'Avenue Didouche Mourad',
    commune: 'Skikda',
    wilaya: 'Skikda',
    wilayaCode: '21',
    phone: '038 75 14 90',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.879,
    lng: 6.908,
  },
  {
    id: 'ski-02',
    name: 'Pharmacie Collo Baie',
    address: 'Rue du Port',
    commune: 'Collo',
    wilaya: 'Skikda',
    wilayaCode: '21',
    phone: '038 70 21 09',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 37.008,
    lng: 6.562,
  },

  // 22 - Sidi Bel Abbès
  {
    id: 'sba-01',
    name: 'Pharmacie Tessala',
    address: 'Boulevard de la Macta',
    commune: 'Sidi Bel Abbès',
    wilaya: 'Sidi Bel Abbès',
    wilayaCode: '22',
    phone: '048 65 30 11',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.192,
    lng: -0.632,
  },
  {
    id: 'sba-02',
    name: 'Pharmacie Telagh',
    address: 'Rue de la Gare',
    commune: 'Telagh',
    wilaya: 'Sidi Bel Abbès',
    wilayaCode: '22',
    phone: '048 72 14 02',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 34.782,
    lng: -0.571,
  },

  // 23 - Annaba
  {
    id: 'ann-01',
    name: 'Pharmacie Cours de la Révolution',
    address: '8, Cours de la Révolution',
    commune: 'Annaba',
    wilaya: 'Annaba',
    wilayaCode: '23',
    phone: '038 86 12 34',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.902,
    lng: 7.765,
  },
  {
    id: 'ann-02',
    name: 'Pharmacie El Bouni Santé',
    address: 'Boulevard du 1er Mai',
    commune: 'El Bouni',
    wilaya: 'Annaba',
    wilayaCode: '23',
    phone: '038 52 40 18',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.861,
    lng: 7.734,
  },

  // 24 - Guelma
  {
    id: 'gue-01',
    name: 'Pharmacie Calama',
    address: 'Place du 19 Mars',
    commune: 'Guelma',
    wilaya: 'Guelma',
    wilayaCode: '24',
    phone: '037 20 18 55',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.463,
    lng: 7.431,
  },
  {
    id: 'gue-02',
    name: 'Pharmacie Hammam Debagh',
    address: 'Rue des Thermes',
    commune: 'Hammam Debagh',
    wilaya: 'Guelma',
    wilayaCode: '24',
    phone: '037 26 10 40',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.458,
    lng: 7.271,
  },

  // 25 - Constantine
  {
    id: 'cst-01',
    name: 'Pharmacie Pont Suspendu',
    address: '15, rue Larbi Ben M’hidi',
    commune: 'Constantine',
    wilaya: 'Constantine',
    wilayaCode: '25',
    phone: '031 92 45 67',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.365,
    lng: 6.614,
  },
  {
    id: 'cst-02',
    name: 'Pharmacie Ali Mendjeli Nouvelle Ville',
    address: 'UV 5, Bâtiment 12',
    commune: 'El Khroub',
    wilaya: 'Constantine',
    wilayaCode: '25',
    phone: '031 78 90 12',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.261,
    lng: 6.574,
  },

  // 26 - Médéa
  {
    id: 'med-01',
    name: 'Pharmacie Titteri',
    address: 'Boulevard de l’ALN',
    commune: 'Médéa',
    wilaya: 'Médéa',
    wilayaCode: '26',
    phone: '025 58 19 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.268,
    lng: 2.754,
  },
  {
    id: 'med-02',
    name: 'Pharmacie Berrouaghia',
    address: 'Rue Didouche Mourad',
    commune: 'Berrouaghia',
    wilaya: 'Médéa',
    wilayaCode: '26',
    phone: '025 77 12 04',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.136,
    lng: 2.912,
  },

  // 27 - Mostaganem
  {
    id: 'mos-01',
    name: 'Pharmacie Salam Andar',
    address: '16, rue de la République',
    commune: 'Mostaganem',
    wilaya: 'Mostaganem',
    wilayaCode: '27',
    phone: '045 21 63 87',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.932,
    lng: 0.089,
  },
  {
    id: 'mos-02',
    name: 'Pharmacie Kharouba Plage',
    address: 'Boulevard de l’ALN',
    commune: 'Mostaganem',
    wilaya: 'Mostaganem',
    wilayaCode: '27',
    phone: '045 26 94 12',
    garde: 'rotation',
    hours: 'Garde en rotation',
    lat: 35.952,
    lng: 0.114,
  },

  // 28 - M'Sila
  {
    id: 'msi-01',
    name: 'Pharmacie Hodna',
    address: 'Avenue de l’Indépendance',
    commune: "M'Sila",
    wilaya: "M'Sila",
    wilayaCode: '28',
    phone: '035 55 18 20',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.705,
    lng: 4.542,
  },
  {
    id: 'msi-02',
    name: 'Pharmacie Boussaâda Oasis',
    address: 'Rue Kerdada',
    commune: 'Boussaâda',
    wilaya: "M'Sila",
    wilayaCode: '28',
    phone: '035 52 30 15',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.214,
    lng: 4.175,
  },

  // 29 - Mascara
  {
    id: 'mas-01',
    name: 'Pharmacie Emir Abdelkader',
    address: 'Boulevard Pasteur',
    commune: 'Mascara',
    wilaya: 'Mascara',
    wilayaCode: '29',
    phone: '045 80 14 22',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.398,
    lng: 0.141,
  },
  {
    id: 'mas-02',
    name: 'Pharmacie Sig Plaine',
    address: 'Avenue de la Liberté',
    commune: 'Sig',
    wilaya: 'Mascara',
    wilayaCode: '29',
    phone: '045 85 20 18',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.531,
    lng: -0.192,
  },

  // 30 - Ouargla
  {
    id: 'oua-01',
    name: 'Pharmacie Oasis Palmeraie',
    address: 'Avenue de la République',
    commune: 'Ouargla',
    wilaya: 'Ouargla',
    wilayaCode: '30',
    phone: '029 71 12 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 31.954,
    lng: 5.325,
  },
  {
    id: 'oua-02',
    name: 'Pharmacie Hassi Messaoud Pétrole',
    address: 'Zone Industrielle Base 24',
    commune: 'Hassi Messaoud',
    wilaya: 'Ouargla',
    wilayaCode: '30',
    phone: '029 73 50 18',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 31.698,
    lng: 6.072,
  },

  // 31 - Oran
  {
    id: 'ora-01',
    name: 'Pharmacie Front de Mer',
    address: '24, boulevard de l’ALN',
    commune: 'Oran',
    wilaya: 'Oran',
    wilayaCode: '31',
    phone: '041 33 22 11',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.702,
    lng: -0.635,
  },
  {
    id: 'ora-02',
    name: 'Pharmacie Akid Lotfi Santé',
    address: 'Boulevard Akid Lotfi',
    commune: 'Bir El Djir',
    wilaya: 'Oran',
    wilayaCode: '31',
    phone: '041 42 19 80',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.719,
    lng: -0.589,
  },

  // 32 - El Bayadh
  {
    id: 'elb-01',
    name: 'Pharmacie Ksour Express',
    address: 'Avenue de la Victoire',
    commune: 'El Bayadh',
    wilaya: 'El Bayadh',
    wilayaCode: '32',
    phone: '049 71 14 02',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 33.682,
    lng: 1.021,
  },
  {
    id: 'elb-02',
    name: 'Pharmacie Rogassa',
    address: 'Route de Saïda',
    commune: 'Rogassa',
    wilaya: 'El Bayadh',
    wilayaCode: '32',
    phone: '049 74 20 11',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 33.951,
    lng: 0.984,
  },

  // 33 - Illizi
  {
    id: 'ill-01',
    name: 'Pharmacie Tassili N’Ajjer',
    address: 'Avenue Principale',
    commune: 'Illizi',
    wilaya: 'Illizi',
    wilayaCode: '33',
    phone: '029 42 10 90',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 26.485,
    lng: 8.471,
  },
  {
    id: 'ill-02',
    name: 'Pharmacie In Aménas Gaz',
    address: 'Centre Urbain',
    commune: 'In Aménas',
    wilaya: 'Illizi',
    wilayaCode: '33',
    phone: '029 43 21 00',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 28.041,
    lng: 9.562,
  },

  // 34 - Bordj Bou Arréridj
  {
    id: 'bba-01',
    name: 'Pharmacie Bibans Electronique',
    address: 'Avenue Houari Boumediene',
    commune: 'Bordj Bou Arréridj',
    wilaya: 'Bordj Bou Arréridj',
    wilayaCode: '34',
    phone: '035 68 25 10',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.072,
    lng: 4.764,
  },
  {
    id: 'bba-02',
    name: 'Pharmacie Ras El Oued',
    address: 'Rue de la Gare',
    commune: 'Ras El Oued',
    wilaya: 'Bordj Bou Arréridj',
    wilayaCode: '34',
    phone: '035 72 11 40',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.942,
    lng: 5.031,
  },

  // 35 - Boumerdès
  {
    id: 'bmd-01',
    name: 'Pharmacie Rocher Noir',
    address: 'Boulevard de l’ALN',
    commune: 'Boumerdès',
    wilaya: 'Boumerdès',
    wilayaCode: '35',
    phone: '024 81 22 10',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.762,
    lng: 3.475,
  },
  {
    id: 'bmd-02',
    name: 'Pharmacie Dellys Phare',
    address: 'Rue du Port',
    commune: 'Dellys',
    wilaya: 'Boumerdès',
    wilayaCode: '35',
    phone: '024 98 10 44',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 36.917,
    lng: 3.913,
  },

  // 36 - El Tarf
  {
    id: 'elt-01',
    name: 'Pharmacie Parc El Kala',
    address: 'Route Nationale 44',
    commune: 'El Tarf',
    wilaya: 'El Tarf',
    wilayaCode: '36',
    phone: '038 60 14 20',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.768,
    lng: 8.314,
  },
  {
    id: 'elt-02',
    name: 'Pharmacie El Kala Port',
    address: 'Boulevard Front de Mer',
    commune: 'El Kala',
    wilaya: 'El Tarf',
    wilayaCode: '36',
    phone: '038 66 11 90',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.895,
    lng: 8.441,
  },

  // 37 - Tindouf
  {
    id: 'tin-01',
    name: 'Pharmacie Gara Djebilet',
    address: 'Place de l’Indépendance',
    commune: 'Tindouf',
    wilaya: 'Tindouf',
    wilayaCode: '37',
    phone: '049 92 10 50',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 27.674,
    lng: -8.142,
  },
  {
    id: 'tin-02',
    name: 'Pharmacie Oum El Achar',
    address: 'Avenue de la Paix',
    commune: 'Tindouf',
    wilaya: 'Tindouf',
    wilayaCode: '37',
    phone: '049 92 35 12',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 27.685,
    lng: -8.131,
  },

  // 38 - Tissemsilt
  {
    id: 'tis-01',
    name: 'Pharmacie Ouarsenis Cèdres',
    address: 'Boulevard Mohamed Boudiaf',
    commune: 'Tissemsilt',
    wilaya: 'Tissemsilt',
    wilayaCode: '38',
    phone: '046 47 18 20',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.604,
    lng: 1.812,
  },
  {
    id: 'tis-02',
    name: 'Pharmacie Théodule',
    address: 'Rue de la Victoire',
    commune: 'Theniet El Had',
    wilaya: 'Tissemsilt',
    wilayaCode: '38',
    phone: '046 49 10 11',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.871,
    lng: 2.029,
  },

  // 39 - El Oued
  {
    id: 'elo-01',
    name: 'Pharmacie Mille Coupoles',
    address: 'Boulevard de l’ALN',
    commune: 'El Oued',
    wilaya: 'El Oued',
    wilayaCode: '39',
    phone: '032 21 15 80',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 33.372,
    lng: 6.864,
  },
  {
    id: 'elo-02',
    name: 'Pharmacie Guemar Oasis',
    address: 'Route Nationale 48',
    commune: 'Guemar',
    wilaya: 'El Oued',
    wilayaCode: '39',
    phone: '032 24 10 19',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 33.491,
    lng: 6.798,
  },

  // 40 - Khenchela
  {
    id: 'khe-01',
    name: 'Pharmacie Mascula',
    address: 'Avenue de la Paix',
    commune: 'Khenchela',
    wilaya: 'Khenchela',
    wilayaCode: '40',
    phone: '032 32 10 14',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.431,
    lng: 7.142,
  },
  {
    id: 'khe-02',
    name: 'Pharmacie Kaïs Aurès',
    address: 'Rue Principale',
    commune: 'Kaïs',
    wilaya: 'Khenchela',
    wilayaCode: '40',
    phone: '032 36 21 00',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 35.501,
    lng: 6.924,
  },

  // 41 - Souk Ahras
  {
    id: 'sou-01',
    name: 'Pharmacie Taghaste Saint-Augustin',
    address: 'Boulevard de la République',
    commune: 'Souk Ahras',
    wilaya: 'Souk Ahras',
    wilayaCode: '41',
    phone: '037 32 19 80',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.284,
    lng: 7.951,
  },
  {
    id: 'sou-02',
    name: 'Pharmacie Sedrata',
    address: 'Rue de Constantine',
    commune: 'Sedrata',
    wilaya: 'Souk Ahras',
    wilayaCode: '41',
    phone: '037 37 10 12',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.128,
    lng: 7.531,
  },

  // 42 - Tipaza
  {
    id: 'tip-01',
    name: 'Pharmacie Chenoua Baie',
    address: 'Route Nationale 11',
    commune: 'Tipaza',
    wilaya: 'Tipaza',
    wilayaCode: '42',
    phone: '024 49 12 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.592,
    lng: 2.441,
  },
  {
    id: 'tip-02',
    name: 'Pharmacie Cherchell Port',
    address: 'Avenue de Césarée',
    commune: 'Cherchell',
    wilaya: 'Tipaza',
    wilayaCode: '42',
    phone: '024 43 20 18',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.608,
    lng: 2.194,
  },

  // 43 - Mila
  {
    id: 'mil-01',
    name: 'Pharmacie Fontaine Romaine',
    address: 'Boulevard du 1er Novembre',
    commune: 'Mila',
    wilaya: 'Mila',
    wilayaCode: '43',
    phone: '031 57 18 90',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.451,
    lng: 6.262,
  },
  {
    id: 'mil-02',
    name: 'Pharmacie Chelghoum Laïd',
    address: 'Rue de Constantine',
    commune: 'Chelghoum Laïd',
    wilaya: 'Mila',
    wilayaCode: '43',
    phone: '031 52 10 44',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.162,
    lng: 6.171,
  },

  // 44 - Aïn Defla
  {
    id: 'aid-01',
    name: 'Pharmacie Zaccar',
    address: 'Boulevard de la République',
    commune: 'Aïn Defla',
    wilaya: 'Aïn Defla',
    wilayaCode: '44',
    phone: '027 60 14 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 36.264,
    lng: 1.971,
  },
  {
    id: 'aid-02',
    name: 'Pharmacie Khemis Miliana Centre',
    address: 'Avenue de la Gare',
    commune: 'Khemis Miliana',
    wilaya: 'Aïn Defla',
    wilayaCode: '44',
    phone: '027 66 22 18',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 36.261,
    lng: 2.221,
  },

  // 45 - Naâma
  {
    id: 'naa-01',
    name: 'Pharmacie Tiout Ksour',
    address: 'Avenue Principale',
    commune: 'Naâma',
    wilaya: 'Naâma',
    wilayaCode: '45',
    phone: '049 79 12 10',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 33.268,
    lng: -0.312,
  },
  {
    id: 'naa-02',
    name: 'Pharmacie Mécheria Steppes',
    address: 'Boulevard Pasteur',
    commune: 'Mécheria',
    wilaya: 'Naâma',
    wilayaCode: '45',
    phone: '049 58 20 40',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 33.541,
    lng: -0.279,
  },

  // 46 - Aïn Témouchent
  {
    id: 'ait-01',
    name: 'Pharmacie Syphax',
    address: 'Boulevard de la Révolution',
    commune: 'Aïn Témouchent',
    wilaya: 'Aïn Témouchent',
    wilayaCode: '46',
    phone: '048 70 18 22',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.301,
    lng: -1.142,
  },
  {
    id: 'ait-02',
    name: 'Pharmacie Béni Saf Port',
    address: 'Rue de la Marine',
    commune: 'Béni Saf',
    wilaya: 'Aïn Témouchent',
    wilayaCode: '46',
    phone: '048 74 11 05',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 35.302,
    lng: -1.382,
  },

  // 47 - Ghardaïa
  {
    id: 'gha-01',
    name: 'Pharmacie M’zab Rostomides',
    address: 'Place du Marché',
    commune: 'Ghardaïa',
    wilaya: 'Ghardaïa',
    wilayaCode: '47',
    phone: '029 88 15 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 32.492,
    lng: 3.674,
  },
  {
    id: 'gha-02',
    name: 'Pharmacie El Guerrara',
    address: 'Route de Touggourt',
    commune: 'El Guerrara',
    wilaya: 'Ghardaïa',
    wilayaCode: '47',
    phone: '029 84 10 22',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 32.791,
    lng: 4.492,
  },

  // 48 - Relizane
  {
    id: 'rel-01',
    name: 'Pharmacie Mina',
    address: 'Boulevard de la République',
    commune: 'Relizane',
    wilaya: 'Relizane',
    wilayaCode: '48',
    phone: '046 92 14 50',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 35.742,
    lng: 0.552,
  },
  {
    id: 'rel-02',
    name: 'Pharmacie Oued Rhiou',
    address: 'Rue de la Gare',
    commune: 'Oued Rhiou',
    wilaya: 'Relizane',
    wilayaCode: '48',
    phone: '046 96 11 09',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 35.962,
    lng: 0.918,
  },

  // 49 - Timimoun
  {
    id: 'tmm-01',
    name: 'Pharmacie Oasis Rouge',
    address: 'Boulevard Gourara',
    commune: 'Timimoun',
    wilaya: 'Timimoun',
    wilayaCode: '49',
    phone: '049 90 12 40',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 29.263,
    lng: 0.231,
  },
  {
    id: 'tmm-02',
    name: 'Pharmacie Aougrout',
    address: 'Route de Reggane',
    commune: 'Aougrout',
    wilaya: 'Timimoun',
    wilayaCode: '49',
    phone: '049 90 88 12',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 28.742,
    lng: 0.252,
  },

  // 50 - Bordj Badji Mokhtar
  {
    id: 'bbm-01',
    name: 'Pharmacie Frontière Sud',
    address: 'Avenue Principale',
    commune: 'Bordj Badji Mokhtar',
    wilaya: 'Bordj Badji Mokhtar',
    wilayaCode: '50',
    phone: '029 36 10 20',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 21.332,
    lng: 0.952,
  },
  {
    id: 'bbm-02',
    name: 'Pharmacie Timiaouine',
    address: 'Route Transsaharienne',
    commune: 'Timiaouine',
    wilaya: 'Bordj Badji Mokhtar',
    wilayaCode: '50',
    phone: '029 36 40 11',
    garde: 'rotation',
    hours: 'Garde en rotation',
    lat: 20.431,
    lng: 1.812,
  },

  // 51 - Ouled Djellal
  {
    id: 'odj-01',
    name: 'Pharmacie Deglet Nour',
    address: 'Avenue de la Liberté',
    commune: 'Ouled Djellal',
    wilaya: 'Ouled Djellal',
    wilayaCode: '51',
    phone: '033 70 12 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 34.425,
    lng: 5.074,
  },
  {
    id: 'odj-02',
    name: 'Pharmacie Sidi Khaled',
    address: 'Place Publique',
    commune: 'Sidi Khaled',
    wilaya: 'Ouled Djellal',
    wilayaCode: '51',
    phone: '033 70 55 19',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 34.382,
    lng: 4.981,
  },

  // 52 - Béni Abbès
  {
    id: 'ben-01',
    name: 'Pharmacie Perle de la Saoura',
    address: 'Boulevard Charles de Foucauld',
    commune: 'Béni Abbès',
    wilaya: 'Béni Abbès',
    wilayaCode: '52',
    phone: '049 84 10 15',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 30.134,
    lng: -2.171,
  },
  {
    id: 'ben-02',
    name: 'Pharmacie Kerzaz',
    address: 'Route Nationale 6',
    commune: 'Kerzaz',
    wilaya: 'Béni Abbès',
    wilayaCode: '52',
    phone: '049 84 60 12',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 29.452,
    lng: -1.412,
  },

  // 53 - In Salah
  {
    id: 'ins-01',
    name: 'Pharmacie Tidikelt Soleil',
    address: 'Place du 1er Mai',
    commune: 'In Salah',
    wilaya: 'In Salah',
    wilayaCode: '53',
    phone: '029 37 11 40',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 27.201,
    lng: 2.464,
  },
  {
    id: 'ins-02',
    name: 'Pharmacie Foggaret Ezzaouia',
    address: 'Avenue Principale',
    commune: 'Foggaret Ezzaouia',
    wilaya: 'In Salah',
    wilayaCode: '53',
    phone: '029 37 40 22',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 27.312,
    lng: 2.821,
  },

  // 54 - In Guezzam
  {
    id: 'ing-01',
    name: 'Pharmacie Porte du Sahel',
    address: 'Avenue de l’Unité Africaine',
    commune: 'In Guezzam',
    wilaya: 'In Guezzam',
    wilayaCode: '54',
    phone: '029 39 10 05',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 19.572,
    lng: 5.771,
  },
  {
    id: 'ing-02',
    name: 'Pharmacie Tin Zaouatine',
    address: 'Route Frontalière',
    commune: 'Tin Zaouatine',
    wilaya: 'In Guezzam',
    wilayaCode: '54',
    phone: '029 39 30 18',
    garde: 'rotation',
    hours: 'Garde en rotation',
    lat: 19.954,
    lng: 2.961,
  },

  // 55 - Touggourt
  {
    id: 'tou-01',
    name: 'Pharmacie Oued Righ',
    address: 'Boulevard de la République',
    commune: 'Touggourt',
    wilaya: 'Touggourt',
    wilayaCode: '55',
    phone: '029 67 18 30',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 33.104,
    lng: 6.062,
  },
  {
    id: 'tou-02',
    name: 'Pharmacie Temacine',
    address: 'Rue de la Zaouïa',
    commune: 'Temacine',
    wilaya: 'Touggourt',
    wilayaCode: '55',
    phone: '029 68 10 15',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 33.021,
    lng: 6.024,
  },

  // 56 - Djanet
  {
    id: 'dja-01',
    name: 'Pharmacie Tassili Oasis',
    address: 'Avenue de la Paix',
    commune: 'Djanet',
    wilaya: 'Djanet',
    wilayaCode: '56',
    phone: '029 47 12 18',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 24.554,
    lng: 9.482,
  },
  {
    id: 'dja-02',
    name: 'Pharmacie Bordj El Haouas',
    address: 'Route Nationale 3',
    commune: 'Bordj El Haouas',
    wilaya: 'Djanet',
    wilayaCode: '56',
    phone: '029 47 50 09',
    garde: 'jour',
    hours: 'Garde de jour : 8h – 20h',
    lat: 25.021,
    lng: 8.641,
  },

  // 57 - El M'Ghair
  {
    id: 'mgh-01',
    name: 'Pharmacie Chott Melghir',
    address: 'Boulevard de l’ALN',
    commune: "El M'Ghair",
    wilaya: "El M'Ghair",
    wilayaCode: '57',
    phone: '032 28 14 20',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 33.952,
    lng: 5.921,
  },
  {
    id: 'mgh-02',
    name: 'Pharmacie Djamaa Oasis',
    address: 'Avenue Principale',
    commune: 'Djamaa',
    wilaya: "El M'Ghair",
    wilayaCode: '57',
    phone: '032 29 10 33',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 33.534,
    lng: 5.992,
  },

  // 58 - El Meniaa
  {
    id: 'men-01',
    name: 'Pharmacie Oasis Blanche',
    address: 'Boulevard Pasteur',
    commune: 'El Meniaa',
    wilaya: 'El Meniaa',
    wilayaCode: '58',
    phone: '029 81 12 40',
    garde: '24h',
    hours: 'Ouverte 24h/24',
    lat: 30.582,
    lng: 2.884,
  },
  {
    id: 'men-02',
    name: 'Pharmacie Hassi Gara',
    address: 'Route Transsaharienne',
    commune: 'Hassi Gara',
    wilaya: 'El Meniaa',
    wilayaCode: '58',
    phone: '029 81 50 18',
    garde: 'nuit',
    hours: 'Garde de nuit : 20h – 8h',
    lat: 30.512,
    lng: 2.915,
  },
]

/** Wilayas couvertes par l'annuaire (les 58 wilayas d'Algérie), avec leur nombre de pharmacies. */
export const PHARMACY_WILAYAS: Array<{ wilaya: string; wilayaCode: string; count: number }> = (() => {
  const map = new Map<string, { wilayaCode: string; count: number }>()
  for (const p of PHARMACY_DIRECTORY) {
    const existing = map.get(p.wilaya)
    if (existing) {
      existing.count += 1
    } else {
      map.set(p.wilaya, { wilayaCode: p.wilayaCode, count: 1 })
    }
  }
  return [...map.entries()]
    .map(([wilaya, data]) => ({ wilaya, wilayaCode: data.wilayaCode, count: data.count }))
    .sort((a, b) => parseInt(a.wilayaCode, 10) - parseInt(b.wilayaCode, 10))
})()
