import type { PaletteDefinition } from './types'

export const PALETTES: PaletteDefinition[] = [
  {
    id: 'porcelain',
    name: 'Porcelaine Suisse',
    tagline: 'Standard Clinique Épuré',
    description: 'Minimalisme clinique suisse à haute lisibilité. Fond gris porcelaine anti-reflets et saphir médical.',
    category: 'clinique',
    colors: {
      bg: '#ebedf2',
      card: '#ffffff',
      primary: '#026aa7',
      chifa: '#047857',
      border: '#d0d7e2',
      text: '#0f172a',
    },
  },
  {
    id: 'nordic-linen',
    name: 'Lin Nordique & Encre',
    tagline: 'Éditorial Papier Chaud',
    description: 'Inspiré des revues médicales prestigieuses (The Lancet). Teinte lin reposante, zéro éblouissement.',
    category: 'chaleur',
    colors: {
      bg: '#f0ede6',
      card: '#faf8f5',
      primary: '#1d4ed8',
      chifa: '#047857',
      border: '#d8d1c3',
      text: '#1c1917',
    },
  },
  {
    id: 'zinc-studio',
    name: 'Zinc Satiné & Glacier',
    tagline: 'Style Linear & Raycast',
    description: 'Esthétique studio scandinave. Fond zinc velouté, contraste technique net et bleu glacier précis.',
    category: 'moderne',
    colors: {
      bg: '#e8ebf0',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#059669',
      border: '#cad2de',
      text: '#090d16',
    },
  },
  {
    id: 'sage-botanical',
    name: 'Sauge & Pin Médical',
    tagline: 'Sérénité & Phytothérapie',
    description: 'Vert sauge apaisant conçu pour réduire la fatigue oculaire et le stress cognitif lors d’usages prolongés.',
    category: 'nature',
    colors: {
      bg: '#edf2ee',
      card: '#f9fbf9',
      primary: '#16654f',
      chifa: '#059669',
      border: '#c9d5cb',
      text: '#14221b',
    },
  },
  {
    id: 'french-cobalt',
    name: 'Craie & Cobalt',
    tagline: 'Codex Officine Française',
    description: 'Blanc craie pur et cobalt éclatant. Lisibilité chirurgicale et contraste franc pour les professionnels.',
    category: 'clinique',
    colors: {
      bg: '#f1f3f7',
      card: '#ffffff',
      primary: '#2563eb',
      chifa: '#059669',
      border: '#cfd5e3',
      text: '#0b1329',
    },
  },
  {
    id: 'sahara-cedar',
    name: 'Dune & Cèdre de l’Atlas',
    tagline: 'Héritage Algérien Solaire',
    description: 'Harmonie des dunes sahariennes et du vert cèdre d’Afrique du Nord. Chaleureux, distinctif et noble.',
    category: 'chaleur',
    colors: {
      bg: '#f4f0e8',
      card: '#fbf9f5',
      primary: '#2d5a36',
      chifa: '#059669',
      border: '#d8cfbe',
      text: '#211c16',
    },
  },
  {
    id: 'braun-mineral',
    name: 'Gris Minéral & Graphite',
    tagline: 'Minimalisme Dieter Rams',
    description: 'Dépouillement monochrome allemand, neutralité absolue et ponctuation cyan minéral.',
    category: 'moderne',
    colors: {
      bg: '#eeeee9',
      card: '#ffffff',
      primary: '#0e7490',
      chifa: '#047857',
      border: '#cbcbc4',
      text: '#18181b',
    },
  },
  {
    id: 'polar-indigo',
    name: 'Brume Polaire & Indigo',
    tagline: 'Biotech & Intelligence IA',
    description: 'Nuance froide et profond indigo. Ambiance laboratoire de recherche clinique et analyse pharmacologique.',
    category: 'moderne',
    colors: {
      bg: '#eceff5',
      card: '#ffffff',
      primary: '#4338ca',
      chifa: '#0f766e',
      border: '#c8d1e0',
      text: '#0f172a',
    },
  },
  {
    id: 'mediterranean-azure',
    name: 'Perle & Azur d’Alger',
    tagline: 'Fraîcheur Méditerranéenne',
    description: 'Gris perle lumineux et bleu marin méditerranéen. Aérien, vivifiant et extrêmement soigné.',
    category: 'nature',
    colors: {
      bg: '#ebf0f5',
      card: '#ffffff',
      primary: '#0369a1',
      chifa: '#047857',
      border: '#c2d2e3',
      text: '#0c1a2e',
    },
  },
  {
    id: 'ivory-emerald',
    name: 'Ivoire Impérial & Émeraude',
    tagline: 'Apothicaire de Prestige',
    description: 'Base ivoire soyeuse mariée à une émeraude impériale et des touches ambrées Chifa. Raffinement maximal.',
    category: 'chaleur',
    colors: {
      bg: '#f2efe7',
      card: '#faf8f3',
      primary: '#065f46',
      chifa: '#047857',
      border: '#d4ccbd',
      text: '#172017',
    },
  },
]
