import type { PaletteDefinition } from './types'

export const PALETTES: PaletteDefinition[] = [
  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 1 : MINIMALISTE & ANTI-FATIGUE (10 PALETTES)             */
  /* ------------------------------------------------------------------ */
  {
    id: 'porcelain',
    name: 'Porcelaine Suisse',
    tagline: 'Standard Clinique Épuré',
    description: 'Minimalisme clinique suisse à haute lisibilité. Fond gris porcelaine anti-reflets et saphir médical.',
    category: 'minimalist',
    badge: 'Clinique',
    colors: {
      bg: '#ebedf2',
      card: '#ffffff',
      primary: '#026aa7',
      chifa: '#047857',
      border: '#d0d7e2',
      text: '#0f172a',
    },
  },
  {
    id: 'nordic-linen',
    name: 'Lin Nordique & Encre',
    tagline: 'Éditorial Papier Chaud',
    description: 'Inspiré des revues médicales prestigieuses (The Lancet). Teinte lin reposante, zéro éblouissement.',
    category: 'minimalist',
    badge: 'Chaleur',
    colors: {
      bg: '#f0ede6',
      card: '#faf8f5',
      primary: '#1d4ed8',
      chifa: '#047857',
      border: '#d8d1c3',
      text: '#1c1917',
    },
  },
  {
    id: 'zinc-studio',
    name: 'Zinc Satiné & Glacier',
    tagline: 'Style Linear & Raycast',
    description: 'Esthétique studio scandinave. Fond zinc velouté, contraste technique net et bleu glacier précis.',
    category: 'minimalist',
    badge: 'Ingénierie',
    colors: {
      bg: '#e8ebf0',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#059669',
      border: '#cad2de',
      text: '#090d16',
    },
  },
  {
    id: 'sage-botanical',
    name: 'Sauge & Pin Médical',
    tagline: 'Sérénité & Phytothérapie',
    description: 'Vert sauge apaisant conçu pour réduire la fatigue oculaire et le stress cognitif lors d’usages prolongés.',
    category: 'minimalist',
    badge: 'Botanique',
    colors: {
      bg: '#edf2ee',
      card: '#f9fbf9',
      primary: '#16654f',
      chifa: '#059669',
      border: '#c9d5cb',
      text: '#14221b',
    },
  },
  {
    id: 'french-cobalt',
    name: 'Craie & Cobalt',
    tagline: 'Codex Officine Française',
    description: 'Blanc craie pur et cobalt éclatant. Lisibilité chirurgicale et contraste franc pour les professionnels.',
    category: 'minimalist',
    badge: 'Officine',
    colors: {
      bg: '#f1f3f7',
      card: '#ffffff',
      primary: '#2563eb',
      chifa: '#059669',
      border: '#cfd5e3',
      text: '#0b1329',
    },
  },
  {
    id: 'sahara-cedar',
    name: 'Dune & Cèdre de l’Atlas',
    tagline: 'Héritage Algérien Solaire',
    description: 'Harmonie des dunes sahariennes et du vert cèdre d’Afrique du Nord. Chaleureux, distinctif et noble.',
    category: 'minimalist',
    badge: 'Algérie',
    colors: {
      bg: '#f4f0e8',
      card: '#fbf9f5',
      primary: '#2d5a36',
      chifa: '#059669',
      border: '#d8cfbe',
      text: '#211c16',
    },
  },
  {
    id: 'braun-mineral',
    name: 'Gris Minéral & Graphite',
    tagline: 'Minimalisme Dieter Rams',
    description: 'Dépouillement monochrome allemand, neutralité absolue et ponctuation cyan minéral.',
    category: 'minimalist',
    badge: 'Monochrome',
    colors: {
      bg: '#eeeee9',
      card: '#ffffff',
      primary: '#0e7490',
      chifa: '#047857',
      border: '#cbcbc4',
      text: '#18181b',
    },
  },
  {
    id: 'polar-indigo',
    name: 'Brume Polaire & Indigo',
    tagline: 'Biotech & Intelligence IA',
    description: 'Nuance froide et profond indigo. Ambiance laboratoire de recherche clinique et analyse pharmacologique.',
    category: 'minimalist',
    badge: 'Biotech',
    colors: {
      bg: '#eceff5',
      card: '#ffffff',
      primary: '#4338ca',
      chifa: '#0f766e',
      border: '#c8d1e0',
      text: '#0f172a',
    },
  },
  {
    id: 'mediterranean-azure',
    name: 'Perle & Azur d’Alger',
    tagline: 'Fraîcheur Méditerranéenne',
    description: 'Gris perle lumineux et bleu marin méditerranéen. Aérien, vivifiant et extrêmement soigné.',
    category: 'minimalist',
    badge: 'Maritime',
    colors: {
      bg: '#ebf0f5',
      card: '#ffffff',
      primary: '#0369a1',
      chifa: '#047857',
      border: '#c2d2e3',
      text: '#0c1a2e',
    },
  },
  {
    id: 'ivory-emerald',
    name: 'Ivoire Impérial & Émeraude',
    tagline: 'Apothicaire de Prestige',
    description: 'Base ivoire soyeuse mariée à une émeraude impériale et des touches ambrées Chifa. Raffinement maximal.',
    category: 'minimalist',
    badge: 'Prestige',
    colors: {
      bg: '#f2efe7',
      card: '#faf8f3',
      primary: '#065f46',
      chifa: '#047857',
      border: '#d4ccbd',
      text: '#172017',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 2 : AUDACIEUX & AVANT-GARDE (10 NOUVELLES PALETTES)      */
  /* ------------------------------------------------------------------ */
  {
    id: 'cyber-synth',
    name: 'Cyber-Med & Bio-Néon',
    tagline: 'Futurisme Synthwave',
    description: 'Interface de bio-hacker du XXIe siècle. Fond lilas givré, néon violet électrique et cyan luminescent.',
    category: 'expressive',
    badge: 'Cyberpunk',
    colors: {
      bg: '#f3f0fb',
      card: '#ffffff',
      primary: '#7c3aed',
      chifa: '#06b6d4',
      border: '#ddd6fe',
      text: '#1e1138',
    },
  },
  {
    id: 'oasis-jasmin',
    name: 'Jasmin d’Alger & Mandarine',
    tagline: 'Parfums d’Oasis Solaire',
    description: 'Inspiré des vergers de la Mitidja. Fond fleur de jasmin poudré, mandarine sanguine et menthe vive.',
    category: 'expressive',
    badge: 'Méditerranée',
    colors: {
      bg: '#fdf5ee',
      card: '#ffffff',
      primary: '#ea580c',
      chifa: '#16a34a',
      border: '#fed7aa',
      text: '#2c1809',
    },
  },
  {
    id: 'alchemy-gold',
    name: 'Lapis-Lazuli & Or Avicenne',
    tagline: 'Codex Alchimiste Antique',
    description: 'Hommage à Ibn Sina et aux traités de pharmacopée d’Orient. Bleu lapis royal intense et or étincelant.',
    category: 'expressive',
    badge: 'Alchimie',
    colors: {
      bg: '#fbf7ee',
      card: '#ffffff',
      primary: '#1e3a8a',
      chifa: '#b45309',
      border: '#e7dec6',
      text: '#172033',
    },
  },
  {
    id: 'abyssal-bio',
    name: 'Bioluminescence Abyssale',
    tagline: 'Profondeurs Océaniques',
    description: 'Pharmacologie marine et organismes abyssaux. Fond écume aquatique, canard abyssal et vert lagon phosphorescent.',
    category: 'expressive',
    badge: 'Océanique',
    colors: {
      bg: '#edf7f6',
      card: '#ffffff',
      primary: '#0f766e',
      chifa: '#10b981',
      border: '#bfe5e0',
      text: '#0a2220',
    },
  },
  {
    id: 'hoggar-sunset',
    name: 'Crépuscule du Hoggar',
    tagline: 'Magie Minérale du Grand Sud',
    description: 'Le crépuscule sur les pitons volcaniques de l’Assekrem. Rose des sables poudré et pourpre amarante intense.',
    category: 'expressive',
    badge: 'Saharien',
    colors: {
      bg: '#fcf2f2',
      card: '#ffffff',
      primary: '#9f1239',
      chifa: '#15803d',
      border: '#fecdd3',
      text: '#2b0b14',
    },
  },
  {
    id: 'aurora-borealis',
    name: 'Aurore Boréale Ionisée',
    tagline: 'Luminescence Polaire',
    description: 'Vapeur de plasma céleste. Menthe boréale ultra-lumineuse, vert ionique et violet ultraviolet magnétique.',
    category: 'expressive',
    badge: 'Cosmique',
    colors: {
      bg: '#eefbf7',
      card: '#ffffff',
      primary: '#059669',
      chifa: '#9333ea',
      border: '#a7f3d0',
      text: '#08231a',
    },
  },
  {
    id: 'silk-amber',
    name: 'Ambre Impérial & Épices',
    tagline: 'Route de la Soie des Apothicaires',
    description: 'Caravanes de précieux remèdes antiques. Teinte safran crémeuse, miel d’ambre chaleureux et jade ancien.',
    category: 'expressive',
    badge: 'Épicé',
    colors: {
      bg: '#fef9ee',
      card: '#ffffff',
      primary: '#d97706',
      chifa: '#047857',
      border: '#fde68a',
      text: '#2c1b05',
    },
  },
  {
    id: 'retro-vapor',
    name: 'Vaporwave Clinique 90s',
    tagline: 'Nostalgie Cyber-Rétro',
    description: 'Pastels technologiques des années 90. Iris violet magnétique, brume lilas douce et cyan arcade lagon.',
    category: 'expressive',
    badge: 'Rétrofutur',
    colors: {
      bg: '#f3f3fd',
      card: '#ffffff',
      primary: '#4f46e5',
      chifa: '#0891b2',
      border: '#c7d2fe',
      text: '#18153b',
    },
  },
  {
    id: 'cardiac-ruby',
    name: 'Rubis Cardiaque & Pouls',
    tagline: 'Énergie Vitale des Urgences',
    description: 'Pulsation de vie et monitorage cardiaque. Fond quartz rose pur, rubis chirurgical noble et vert équilibrant.',
    category: 'expressive',
    badge: 'Cardio',
    colors: {
      bg: '#fef2f2',
      card: '#ffffff',
      primary: '#b91c1c',
      chifa: '#047857',
      border: '#fecaca',
      text: '#2e0909',
    },
  },
  {
    id: 'quartz-rose',
    name: 'Quartz Minéral & Prune',
    tagline: 'Minéralogie de Haute Couture',
    description: 'Cristallographie précieuse et velours précieux. Albâtre poudré, bordeaux prune haute couture et vert sauge.',
    category: 'expressive',
    badge: 'Cristal',
    colors: {
      bg: '#fbf5f4',
      card: '#ffffff',
      primary: '#831843',
      chifa: '#059669',
      border: '#fbcfe8',
      text: '#260b17',
    },
  },
]
