import type { PaletteDefinition } from './types'

export const PALETTES: PaletteDefinition[] = [
  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 1 : NUANCES MINIMALISTES & ANTI-FATIGUE (10 PALETTES)    */
  /* ------------------------------------------------------------------ */
  {
    id: 'porcelain',
    name: 'Porcelaine Suisse',
    tagline: 'Standard Clinique Épuré',
    description: 'Minimalisme clinique suisse à haute lisibilité. Fond gris porcelaine anti-reflets et saphir médical.',
    category: 'minimalist',
    badge: 'Clinique',
    features: ['Rayon 12px', 'Anti-reflets', 'WCAG AAA'],
    colors: {
      bg: '#ebedf2',
      card: '#ffffff',
      primary: '#026aa7',
      chifa: '#047857',
      border: '#d0d7e2',
      text: '#0f172a',
    },
  },
  {
    id: 'nordic-linen',
    name: 'Lin Nordique & Encre',
    tagline: 'Éditorial Papier Chaud',
    description: 'Inspiré des revues médicales prestigieuses (The Lancet). Teinte lin reposante, zéro éblouissement.',
    category: 'minimalist',
    badge: 'Chaleur',
    features: ['Fond lin', 'Zéro éblouissement', 'Éditorial'],
    colors: {
      bg: '#f0ede6',
      card: '#faf8f5',
      primary: '#1d4ed8',
      chifa: '#047857',
      border: '#d8d1c3',
      text: '#1c1917',
    },
  },
  {
    id: 'zinc-studio',
    name: 'Zinc Satiné & Glacier',
    tagline: 'Style Linear & Raycast',
    description: 'Esthétique studio scandinave. Fond zinc velouté, contraste technique net et bleu glacier précis.',
    category: 'minimalist',
    badge: 'Ingénierie',
    features: ['Gris feutré', 'Contraste net', 'Matte'],
    colors: {
      bg: '#e8ebf0',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#059669',
      border: '#cad2de',
      text: '#090d16',
    },
  },
  {
    id: 'sage-botanical',
    name: 'Sauge & Pin Médical',
    tagline: 'Sérénité & Phytothérapie',
    description: 'Vert sauge apaisant conçu pour réduire la fatigue oculaire et le stress cognitif lors d’usages prolongés.',
    category: 'minimalist',
    badge: 'Botanique',
    features: ['Repos oculaire', 'Vert sauge', 'Sérénité'],
    colors: {
      bg: '#edf2ee',
      card: '#f9fbf9',
      primary: '#16654f',
      chifa: '#059669',
      border: '#c9d5cb',
      text: '#14221b',
    },
  },
  {
    id: 'french-cobalt',
    name: 'Craie & Cobalt',
    tagline: 'Codex Officine Française',
    description: 'Blanc craie pur et cobalt éclatant. Lisibilité chirurgicale et contraste franc pour les professionnels.',
    category: 'minimalist',
    badge: 'Officine',
    features: ['Craie pure', 'Cobalt éclatant', 'Netteté'],
    colors: {
      bg: '#f1f3f7',
      card: '#ffffff',
      primary: '#2563eb',
      chifa: '#059669',
      border: '#cfd5e3',
      text: '#0b1329',
    },
  },
  {
    id: 'sahara-cedar',
    name: 'Dune & Cèdre de l’Atlas',
    tagline: 'Héritage Algérien Solaire',
    description: 'Harmonie des dunes sahariennes et du vert cèdre d’Afrique du Nord. Chaleureux, distinctif et noble.',
    category: 'minimalist',
    badge: 'Algérie',
    features: ['Tons sable', 'Cèdre Atlas', 'Chaleureux'],
    colors: {
      bg: '#f4f0e8',
      card: '#fbf9f5',
      primary: '#2d5a36',
      chifa: '#059669',
      border: '#d8cfbe',
      text: '#211c16',
    },
  },
  {
    id: 'braun-mineral',
    name: 'Gris Minéral & Graphite',
    tagline: 'Minimalisme Dieter Rams',
    description: 'Dépouillement monochrome allemand, neutralité absolue et ponctuation cyan minéral.',
    category: 'minimalist',
    badge: 'Monochrome',
    features: ['Neutre pur', 'Rigueur suisse', 'Chirurgical'],
    colors: {
      bg: '#eeeee9',
      card: '#ffffff',
      primary: '#0e7490',
      chifa: '#047857',
      border: '#cbcbc4',
      text: '#18181b',
    },
  },
  {
    id: 'polar-indigo',
    name: 'Brume Polaire & Indigo',
    tagline: 'Biotech & Intelligence IA',
    description: 'Nuance froide et profond indigo. Ambiance laboratoire de recherche clinique et analyse pharmacologique.',
    category: 'minimalist',
    badge: 'Biotech',
    features: ['Brume polaire', 'Indigo profond', 'High-Tech'],
    colors: {
      bg: '#eceff5',
      card: '#ffffff',
      primary: '#4338ca',
      chifa: '#0f766e',
      border: '#c8d1e0',
      text: '#0f172a',
    },
  },
  {
    id: 'mediterranean-azure',
    name: 'Perle & Azur d’Alger',
    tagline: 'Fraîcheur Méditerranéenne',
    description: 'Gris perle lumineux et bleu marin méditerranéen. Aérien, vivifiant et extrêmement soigné.',
    category: 'minimalist',
    badge: 'Maritime',
    features: ['Perle douce', 'Bleu marin', 'Aérien'],
    colors: {
      bg: '#ebf0f5',
      card: '#ffffff',
      primary: '#0369a1',
      chifa: '#047857',
      border: '#c2d2e3',
      text: '#0c1a2e',
    },
  },
  {
    id: 'ivory-emerald',
    name: 'Ivoire Impérial & Émeraude',
    tagline: 'Apothicaire de Prestige',
    description: 'Base ivoire soyeuse mariée à une émeraude impériale et des touches ambrées Chifa. Raffinement maximal.',
    category: 'minimalist',
    badge: 'Prestige',
    features: ['Ivoire soie', 'Émeraude royale', 'Raffiné'],
    colors: {
      bg: '#f2efe7',
      card: '#faf8f3',
      primary: '#065f46',
      chifa: '#047857',
      border: '#d4ccbd',
      text: '#172017',
    },
  },

  /* ------------------------------------------------------------------ */
  /* CATÉGORIE 2 : SYSTÈMES & ARCHITECTURES DE DESIGN (10 DESIGNS)      */
  /* ------------------------------------------------------------------ */
  {
    id: 'design-brutalist',
    name: 'Néo-Brutalisme Chirurgical',
    tagline: 'Angles 0px & Ombres Dures',
    description: 'Zéro arrondi, angles droits vifs de 0px, bordures franches 1.5px et ombres portées directes. Rigueur de laboratoire sans concession.',
    category: 'system',
    badge: 'Brutalisme',
    features: ['Angles 0px', 'Ombres dures', 'Bordures 1.5px'],
    colors: {
      bg: '#f4f5f8',
      card: '#ffffff',
      primary: '#1d4ed8',
      chifa: '#059669',
      border: '#94a3b8',
      text: '#0f172a',
    },
  },
  {
    id: 'design-liquid-glass',
    name: 'Verre Liquide & Aéro',
    tagline: 'Translucidité & Rayon 20px',
    description: 'Grands rayons fluides de 20px, cartes en verre givré ultra-translucide (blur 24px), reflets de lumière spéculaires et ombres douces.',
    category: 'system',
    badge: 'Aéro Glass',
    features: ['Rayon 20px', 'Verre dépoli', 'Flou 24px'],
    colors: {
      bg: '#eef3fa',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#10b981',
      border: '#c2d5ec',
      text: '#0b1b30',
    },
  },
  {
    id: 'design-compact-dense',
    name: 'Terminal d’Officine Pro',
    tagline: 'Densité Maximale & Micro-Coins 4px',
    description: 'Conçu pour le comptoir d’officine à haut débit : micro-coins de 4px, encombrement visuel minimal pour afficher le plus de données à l’écran.',
    category: 'system',
    badge: 'Ultra-Dense',
    features: ['Micro-coins 4px', 'Élévation 0px', 'Densité Max'],
    colors: {
      bg: '#ebedf2',
      card: '#ffffff',
      primary: '#0369a1',
      chifa: '#047857',
      border: '#c8d1de',
      text: '#0f172a',
    },
  },
  {
    id: 'design-soft-pebble',
    name: 'Galet Organique & Silicone',
    tagline: 'Formes Rondes 24px & Douceur',
    description: 'Rayons très arrondis de 24px, ombres enveloppantes et toucher tactile façon dispositif médical en silicone stérile.',
    category: 'system',
    badge: 'Pebble UI',
    features: ['Rayon 24px', 'Silicone doux', 'Organique'],
    colors: {
      bg: '#f1f4f8',
      card: '#ffffff',
      primary: '#4f46e5',
      chifa: '#059669',
      border: '#d4dce7',
      text: '#131b2e',
    },
  },
  {
    id: 'design-flat-architect',
    name: 'Ligne Pure & 0 Ombre',
    tagline: 'Design Plat & Cadre 1px',
    description: 'Zéro ombre portée. La hiérarchie est entièrement sculptée par des micro-lignes chirurgicales de 1px et des alternances de plans suisses.',
    category: 'system',
    badge: 'Pure Flat',
    features: ['Zéro ombre', 'Cadre 1px pur', 'Épure suisse'],
    colors: {
      bg: '#ecf0f4',
      card: '#ffffff',
      primary: '#0f766e',
      chifa: '#047857',
      border: '#cad5e2',
      text: '#0f172a',
    },
  },
  {
    id: 'design-volumetric-card',
    name: 'Élévation Volumétrique 3D',
    tagline: 'Profondeur & Lévitation Multi-Couches',
    description: 'Ombres étagées à triple diffusion créant une physicalité forte. Les cartes de prescription et de commande semblent flotter au-dessus du plan.',
    category: 'system',
    badge: '3D Layered',
    features: ['Lévitation 3D', 'Ombres diffuses', 'Physicalité'],
    colors: {
      bg: '#e9ecf2',
      card: '#ffffff',
      primary: '#1e40af',
      chifa: '#047857',
      border: '#c5d0e0',
      text: '#0f172a',
    },
  },
  {
    id: 'design-high-contrast',
    name: 'Haute Accessibilité (WCAG AAA)',
    tagline: 'Bordures Franches & Contraste 12:1',
    description: 'Bordures épaissies de 2px très lisibles, ratios de contraste élevés (> 12:1). Idéal pour les écrans d’officine sous forte lumière du jour.',
    category: 'system',
    badge: 'WCAG AAA',
    features: ['Bordures 2px', 'Contraste 12:1', 'Lisibilité Day'],
    colors: {
      bg: '#e5e9f0',
      card: '#ffffff',
      primary: '#025a9e',
      chifa: '#036044',
      border: '#64748b',
      text: '#090d16',
    },
  },
  {
    id: 'design-telemetry-hud',
    name: 'Cockpit Télémétrique & HUD',
    tagline: 'Moniteur Hospitalier & Visière 3px',
    description: 'Rayon technique de 3px, micro-lignes cyan, sensation de visière de monitoring de soins intensifs et d’imagerie médicale.',
    category: 'system',
    badge: 'HUD Médical',
    features: ['Micro-rayon 3px', 'Cyan moniteur', 'Technique'],
    colors: {
      bg: '#e8edf3',
      card: '#ffffff',
      primary: '#0284c7',
      chifa: '#059669',
      border: '#94a3b8',
      text: '#0b1524',
    },
  },
  {
    id: 'design-paper-codex',
    name: 'Fiches Bristol d’Officine',
    tagline: 'Carton Fort & Encre Bleue',
    description: 'Cartes évoquant les fiches d’ordonnancier en carton bristol. Rayon 8px, fond lin chaud et séparation délicate façon tiroir d’apothicaire.',
    category: 'system',
    badge: 'Bristol Codex',
    features: ['Bristol chaud', 'Encre marine', 'Rayon 8px'],
    colors: {
      bg: '#eee9df',
      card: '#fcfbfa',
      primary: '#1e3a8a',
      chifa: '#2e6930',
      border: '#d5ccbe',
      text: '#1f1a14',
    },
  },
  {
    id: 'design-monochrome-braun',
    name: 'Monochrome Industriel',
    tagline: 'Rigueur Braun & Touche Sécurité',
    description: 'Neutralité absolue de l’ardoise et de l’aluminium. Un unique accent ambre de sécurité fonctionnel pour les actions.',
    category: 'system',
    badge: 'Rams Braun',
    features: ['Rayon 5px', 'Graphite minéral', 'Ambre sécurité'],
    colors: {
      bg: '#eeeeea',
      card: '#ffffff',
      primary: '#d97706',
      chifa: '#15803d',
      border: '#c8c8c2',
      text: '#18181b',
    },
  },
]
