import { db } from "../src/lib/db";
async function main() {
  const dciKeys = ["METFORMINE","AMLODIPINE","RAMIPRIL","LOSARTAN","ATORVASTATINE","OMEPRAZOLE","PANTOPRAZOLE","CETIRIZINE","LORATADINE","SALBUTAMOL","DIAZEPAM","ZOLPIDEM","LEVOTHYROXINE","LEVOTHIROXINE","LOPERAMIDE","LACTULOSE","MACROGOL","DOMPERIDONE","METOCLOPRAMIDE","DEXTRAMETHORPHAN","DEXTROMETHORPHANE","CARBOCISTEINE","FER","VITAMINE","CHOLECALCIFEROL","INSULINE","CLOPIDOGREL","ACIDE ACETYLSALICYLIQUE","ASPIRINE","ETHINYLESTRADIOL","ALBENDAZOLE","FUROSEMIDE","FURSEMIDE","SITAGLIPTINE","GABAPENTINE","AMOXICILLINE","AZITHROMYCINE","CIPROFLOXACINE","CEFIXIME","PARACETAMOL","IBUPROFENE","ANTIBIOTIQUE","ASTHME","ANTALGIQUE","ALLERGIE","CARDIOLOGIE","HYPERTENSION","DIABETE","VITAMINE D","PSEUDOEPHEDRINE","CHLORPHENAMINE","NIFEDIPINE","BISOPROLOL","ESOMEPRAZOLE","SERTRALINE","FLUOXETINE","CITALOPRAM","TRAMADOL","CODERGOTMINE? NO"];
  for (const k of dciKeys) {
    if (k.includes("?")) continue;
    const c = await db.drug.count({ where: { dciKey: { contains: k }, status: "ACTIF" } });
    if (c > 0) console.log(`${k}: ${c}`);
    else console.log(`${k}: --`);
  }
  const brands = ["AUGMENTIN","VENTOLINE","ASPEGIC","ZITHROMAX","LOVENOX","GLUCOPHAGE","AMOXIL","DAFLON","SMECTA","MOTILIUM","BUSCOPAN","SPASFON"];
  for (const b of brands) {
    const c = await db.drug.count({ where: { brandKey: { startsWith: b }, status: "ACTIF" } });
    console.log(`BRAND ${b}: ${c}`);
  }
}
main();
